version: "3"

services:
  infrared:
    image: haveachin/infrared:dev
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    container_name: infrared
    restart: "no"
    ports:
      - 25565:25565/tcp
      - 19132:19132/udp
    volumes:
      - ../dev:/infrared
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - infrared

  minecraft-server:
    image: itzg/minecraft-server:java17
    container_name: minecraft-server
    restart: "no"
    environment:
      EULA: "TRUE"
    networks:
      - infrared
    labels:
      - infrared.java.servers.devserver.gateways=[default]
      - infrared.java.servers.devserver.domains=[*]
      - infrared.java.servers.devserver.address=minecraft-server:25565

networks:
  infrared:
    name: infrared
