version: "3"

services:
  infrared:
    image: haveachin/infrared:latest
    container_name: infrared
    restart: always
    ports:
      # Port for Java Edition
      - 25565:25565/tcp
      # Port for Bedrock Edition
      - 19132:19132/udp
    volumes:
      - ./data/infrared:/infrared
      #- /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - infrared

  #redis:
  #  image: redis
  #  container_name: infrared-redis
  #  restart: always
  #  networks:
  #    - infrared

networks:
  infrared:
    name: infrared